version: "3"

networks:
  whaticket:

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rqrIu8Q6hk9j9mc9TOYu3w
      - MYSQL_DATABASE=whaticket
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - whaticket

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=rqrIu8Q6hk9j9mc9TOYu3w
      - DB_NAME=whaticket
      - JWT_SECRET=P5d6b4mqA3tUdn1-8a-aoMr-r-0OGVY0kys4LYFWbNBlNKdlDQJdcoDde1b_gdRrp2gkZ5zPy5UNwOMQhtA-ng
      - JWT_REFRESH_SECRET=zMWDIBryz6DRHPP5CwOk8eOvUed5TVc83LBlwUulSjyJsXc_919aE3XRwk1cmKPvB_o6STmSqxiO8-DDr1g-lw
      - BACKEND_URL=https://api.cloiuw.com
      - FRONTEND_URL=https://app.cloiuw.com
      - PROXY_PORT=8080
    ports:
      - "8080:3000"
    volumes:
      - ./backend/public/:/usr/src/app/public/
      - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
    depends_on:
      - mysql
    networks:
      - whaticket

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=https://api.cloiuw.com
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - whaticket

volumes:
  db_data:
